# Generated by Django 4.1 on 2022-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Publish")], default="DF", max_length=2
            ),
        ),
    ]
