# Generated by Django 4.1.1 on 2022-09-11 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_category"),
    ]

    operations = [
        migrations.RenameModel(old_name="Blog", new_name="Post",),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_publish_bb7600_idx",
            old_name="blog_blog_publish_1d1149_idx",
        ),
    ]
